### ISSUE TITLE
How do you produce these proxies?

### ISSUE THREAD

**Issue by maobenz** [DanaCohen95/Set-the-Scene#1]
Hello,
It is an awesome work! I want to ask how do you produce these proxies and when will you release the code?

Thanks a lot!

**Comment by DanaCohen95** [comment]
Thank you for your comment!
The code will be released this week. 
There are two ways to produce the proxies:
1. Designing simple shapes using Blender or other 3D software.
2. Downloading shapes - several websites provide free obj files (turbosquid, free3d, etc...).
