### ISSUE TITLE
Set-The-Scene for 360 scenes

### ISSUE THREAD

**Issue by JonasSchult** [DanaCohen95/Set-the-Scene#10]
Hi,

thanks for your amazing work! :)

I see that you use a "quarter" room (floor and 2 walls + objects). I assume that it is important to have inward-facing views.

I am wondering if it is possible to generate a "complete" 360 degree scene with Set-the-scene, that is, 4 walls + floor + ceiling and objects inside this room.

Best,
Jonas

**Comment by DanaCohen95** [comment]
Sure, 360-degree indoor scenes should work without problems.
You only have to change the range of the theta parameter for the global training.

**Comment by JonasSchult** [comment]
Thanks for your answer!
We would still have inward-facing views then, am I right?

Best,
Jonas

**Comment by DanaCohen95** [comment]
yes, you are right :)

**Comment by JonasSchult** [comment]
Thanks for your help Dana! :)
