### ISSUE TITLE
Where is the train.py file?

### ISSUE THREAD

**Issue by Gaowz112** [DanaCohen95/Set-the-Scene#2]
Hi,
Thanks for your excellent work！I want to run "python -m train.py --config demo_configs/scene_name.yaml"，but didn't find where the train.py is. 
Thanks a lot.

**Comment by DanaCohen95** [comment]
Hi!
The training file is 'scripts.train_scene_nerf.py', and the command is
```bash
 python -m scripts.train_scene_nerf --config_path demo_configs/scene_name.yaml
```

 I've updated the README to make it clear.
