### ISSUE TITLE
unintended generation results

### ISSUE THREAD

**Issue by Coinc1dens** [DanaCohen95/Set-the-Scene#3]
Hello, it is a surprising work! While I cannot obtain the intended results when I use the default params and configs to train a scene. Specifically, I used two configs of `living_room` and `dining_room` in `demo_configs` to train 15,000 steps and finally get an empty scene like this. The depth map is like an empty room and RGB image is strange. I wonder if there's anything wrong with my operations?
![15000-rgb](https://i.postimg.cc/jdxqgVD7/15000-rgb-Moment.jpg)
![15000-depth.jpg](https://i.postimg.cc/05fPJtV2/15000-depth-Moment.jpg)

**Comment by DanaCohen95** [comment]
Hi!
During the training, the results are displayed in the vis/train folder. Can you please check if the scene remains empty throughout the entire training process?

**Comment by Coinc1dens** [comment]
The scene remained empty throughout the process, but I've solved this problem by redownloading the files and executing them. Now I get a right scene. Thanks for your reply! :D
